Repository joeycastillo/Sensor-Watch, pull requests merged in 2024-09, with the labels that each got.

#431 Hackwatch: July has 31 days
  movement/watch_faces/settings/set_time_hackwatch_face.c
Labels: bug, next

#433 Swapped the bell and alarm icon on the clock face to match Casio's doc
  movement/watch_faces/clock/clock_face.c
Labels: bug, next

#440 Countdown fix
  movement/watch_faces/complication/countdown_face.c
Labels: bug, next

#458 add Layla tune
  movement/movement_custom_signal_tunes.h
Labels: enhancement, next

#459 add power rangers tune
  movement/movement_custom_signal_tunes.h
Labels: enhancement, next

#460 `next` - 2024-09-01
  apps/beats-time/app.c
  movement/movement.c
  movement/movement.h
  movement/movement_config.h
  movement/movement_custom_signal_tunes.h
  movement/watch_faces/clock/clock_face.c
  movement/watch_faces/clock/simple_clock_face.c
  movement/watch_faces/complication/countdown_face.c
  movement/watch_faces/complication/day_one_face.c
  movement/watch_faces/complication/sunrise_sunset_face.c
  movement/watch_faces/complication/time_left_face.c
  movement/watch_faces/complication/totp_face.h
  movement/watch_faces/settings/preferences_face.c
  movement/watch_faces/settings/set_time_face.c
  movement/watch_faces/settings/set_time_hackwatch_face.c
  watch-library/hardware/watch/watch_deepsleep.c
  watch-library/shared/driver/thermistor_driver.c
  watch-library/shared/watch/watch_private_display.c
  watch-library/shared/watch/watch_utility.c
  watch-library/shared/watch/watch_utility.h
  watch-library/simulator/shell.html
Labels: next, main

#417 Clock face 24h only flag changes
  movement/movement.c
  movement/watch_faces/clock/clock_face.c
  movement/watch_faces/clock/simple_clock_face.c
  movement/watch_faces/settings/preferences_face.c
Labels: enhancement, next

#426 add temp input to simulator
  watch-library/shared/driver/thermistor_driver.c
  watch-library/simulator/shell.html
Labels: enhancement, next

#428 Sunrise sunset presets
  movement/watch_faces/complication/sunrise_sunset_face.c
Labels: bug, next

#434 Can Set 29 on Feb on Leap Years Across All Set Faces
  apps/beats-time/app.c
  movement/watch_faces/complication/day_one_face.c
  movement/watch_faces/complication/time_left_face.c
  movement/watch_faces/settings/set_time_face.c
  movement/watch_faces/settings/set_time_hackwatch_face.c
  watch-library/shared/watch/watch_utility.c
  watch-library/shared/watch/watch_utility.h
Labels: bug, next

#437 Debounce Logic
  movement/movement.c
  movement/movement.h
Labels: enhancement, tested-on-hw, next

#287 Minimal clock face
  movement/make/Makefile
  movement/movement_faces.h
  movement/watch_faces/clock/minimal_clock_face.c
  movement/watch_faces/clock/minimal_clock_face.h
Labels: enhancement, next, watch-face

#293 movement: Add "instant" led_duration option.
  movement/movement.c
  movement/movement.h
  movement/watch_faces/settings/preferences_face.c
Labels: enhancement, tested-on-hw, next

#386 Beeps demo face
  movement/movement_faces.h
  movement/watch_faces/demo/beeps_face.c
  movement/watch_faces/demo/beeps_face.h
Labels: enhancement, tested-on-hw, next, watch-face

#394 Keep light on if interacting
  movement/movement.c
  watch-library/simulator/main.c
Labels: enhancement, next

#398 simon_face: Simon game complication
  make.mk
  movement/make/Makefile
  movement/movement_faces.h
  movement/watch_faces/complication/simon_face.c
  movement/watch_faces/complication/simon_face.h
Labels: enhancement, next, watch-face

#401 Add "close enough"/"fuzzy" watch face
  movement/make/Makefile
  movement/movement_faces.h
  movement/watch_faces/clock/close_enough_clock_face.c
  movement/watch_faces/clock/close_enough_clock_face.h
Labels: enhancement, next, watch-face

#413 New watch face: Alarm Thermometer
  movement/make/Makefile
  movement/movement_faces.h
  movement/watch_faces/sensor/alarm_thermometer_face.c
  movement/watch_faces/sensor/alarm_thermometer_face.h
Labels: enhancement, next, watch-face

#419 Endless runner
  movement/make/Makefile
  movement/movement_faces.h
  movement/watch_faces/complication/endless_runner_face.c
  movement/watch_faces/complication/endless_runner_face.h
Labels: enhancement, next, watch-face

#423 Periodic Table Face (Updated)
  movement/make/Makefile
  movement/movement_faces.h
  movement/watch_faces/complication/periodic_face.c
  movement/watch_faces/complication/periodic_face.h
Labels: enhancement, next, watch-face

#430 Tally Face Changes
  movement/watch_faces/complication/tally_face.c
  movement/watch_faces/complication/tally_face.h
Labels: enhancement, next, watch-face

#436 Added Wordle
  movement/make/Makefile
  movement/movement_faces.h
  movement/watch_faces/complication/wordle_face.c
  movement/watch_faces/complication/wordle_face.h
  movement/watch_faces/complication/wordle_face_dict.h
  utils/wordle_face/wordle_list.py
Labels: enhancement, next, watch-face

#467 adds a short and long harry potter signal
  movement/movement_custom_signal_tunes.h
Labels: enhancement, next, signal-tunes

#469 Merge `next` -- new watch faces before the freeze
  make.mk
  movement/make/Makefile
  movement/movement.c
  movement/movement.h
  movement/movement_config.h
  movement/movement_custom_signal_tunes.h
  movement/movement_faces.h
  movement/watch_faces/clock/clock_face.c
  movement/watch_faces/clock/close_enough_clock_face.c
  movement/watch_faces/clock/close_enough_clock_face.h
  movement/watch_faces/clock/french_revolutionary_face.c
  movement/watch_faces/clock/french_revolutionary_face.h
  movement/watch_faces/clock/minimal_clock_face.c
  movement/watch_faces/clock/minimal_clock_face.h
  movement/watch_faces/clock/repetition_minute_face.c
  movement/watch_faces/clock/simple_clock_bin_led_face.c
  movement/watch_faces/clock/simple_clock_face.c
  movement/watch_faces/clock/weeknumber_clock_face.c
  movement/watch_faces/clock/world_clock2_face.c
  movement/watch_faces/clock/world_clock_face.c
  movement/watch_faces/complication/activity_face.c
  movement/watch_faces/complication/alarm_face.c
  movement/watch_faces/complication/countdown_face.c
  movement/watch_faces/complication/countdown_face.h
  movement/watch_faces/complication/deadline_face.c
  movement/watch_faces/complication/deadline_face.h
  movement/watch_faces/complication/endless_runner_face.c
  movement/watch_faces/complication/endless_runner_face.h
  movement/watch_faces/complication/higher_lower_game_face.c
  movement/watch_faces/complication/higher_lower_game_face.h
  movement/watch_faces/complication/periodic_face.c
  movement/watch_faces/complication/periodic_face.h
  movement/watch_faces/complication/planetary_hours_face.c
  movement/watch_faces/complication/planetary_time_face.c
  movement/watch_faces/complication/simon_face.c
  movement/watch_faces/complication/simon_face.h
  movement/watch_faces/complication/simple_calculator_face.c
  movement/watch_faces/complication/simple_calculator_face.h
  movement/watch_faces/complication/sunrise_sunset_face.c
  movement/watch_faces/complication/tally_face.c
  movement/watch_faces/complication/tally_face.h
  movement/watch_faces/complication/wake_face.c
  movement/watch_faces/complication/wordle_face.c
  movement/watch_faces/complication/wordle_face.h
  movement/watch_faces/complication/wordle_face_dict.h
  movement/watch_faces/demo/beeps_face.c
  movement/watch_faces/demo/beeps_face.h
  movement/watch_faces/demo/lis2dw_logging_face.c
  movement/watch_faces/sensor/alarm_thermometer_face.c
  movement/watch_faces/sensor/alarm_thermometer_face.h
  movement/watch_faces/sensor/thermistor_logging_face.c
  movement/watch_faces/settings/preferences_face.c
  movement/watch_faces/settings/set_time_face.c
  movement/watch_faces/settings/set_time_hackwatch_face.c
  utils/wordle_face/wordle_list.py
  watch-library/simulator/main.c
Labels: enhancement, next, watch-face
